version: '3'
volumes:
  postgres_data_prod:
services:
  app:
    build: ./external_main
    container_name: flask_azz_yt
    command: gunicorn --bind 0.0.0.0:5000 run:app # WSGI server
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./external_main:/app
    expose:
      - 5000
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - ./pg_db:/var/lib/postgresql/data/
    env_file:
      - ./.env
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    build: ./nginx
    ports:
      - 80:80
    restart: always
    volumes:
      - /home/main/static:/home/web/default/static
    depends_on:
      - app
      - pgadmin
